# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autonomy', '0002_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='student_id',
        ),
    ]
