# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('autonomy', '0005_auto_20170203_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='attatch_file',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='%Y/%M/%d/'),
        ),
    ]
