# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('autonomy', '0006_auto_20170204_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='%Y/%M/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='petition',
            name='attatch_file',
        ),
        migrations.AddField(
            model_name='petitionfile',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autonomy.Petition'),
        ),
    ]
