# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 16:54
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('autonomy', '0010_auto_20170204_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionimage',
            name='file',
            field=django_resized.forms.ResizedImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='%Y/%M/%d'),
        ),
    ]
